/*
 * File: app/controller/SeshMapController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Stonedar.controller.SeshMapController', {
    extend: 'Ext.app.Controller',

    config: {
        routes: {
            'map': 'show'
        },

        refs: {
            seshMapPanel: 'container[itemId="SeshMapPanel"]'
        }
    },

    show: function() {
        console.log('mappp');
        var panel = this.getSeshMapPanel();
        var viewport = Stonedar.app.getController("ViewportController").getViewport();

        if(!panel){
            var panel = Ext.create('Stonedar.view.SeshMapPanel');
            viewport.add(panel);
        }
        else{
            viewport.setActiveItem(panel);
        }
    }

});