/*
 * File: app/view/SeshListPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Stonedar.view.SeshListPanel', {
    extend: 'Ext.Container',

    config: {
        itemId: 'SeshListPanel',
        style: 'background-color: grey;',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                itemTpl: [
                    '<div class="listItem">Start Time {time}',
                    '    	<br>',
                    '    meeting place: {place}',
                    '',
                    '',
                    '	<div class="arrowRight"></div>',
                    '</div>',
                    ''
                ],
                pressedCls: 'itemSelected',
                selectedCls: '',
                store: 'Seshes',
                striped: true
            }
        ]
    }

});